//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace horno_datos_servidor.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\\\Users\\\\HYSTOU\\\\Desktop")]
        public string directorio_1 {
            get {
                return ((string)(this["directorio_1"]));
            }
            set {
                this["directorio_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("datos_acero.csv")]
        public string archivo_csv {
            get {
                return ((string)(this["archivo_csv"]));
            }
            set {
                this["archivo_csv"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\\\Users\\\\HYSTOU\\\\Desktop\\\\carpeta\\\\datos_horno_respaldo.csv")]
        public string directorio_res {
            get {
                return ((string)(this["directorio_res"]));
            }
            set {
                this["directorio_res"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("127.0.0.1")]
        public string d_source {
            get {
                return ((string)(this["d_source"]));
            }
            set {
                this["d_source"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3305")]
        public string puerto {
            get {
                return ((string)(this["puerto"]));
            }
            set {
                this["puerto"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("admin")]
        public string db_usuario {
            get {
                return ((string)(this["db_usuario"]));
            }
            set {
                this["db_usuario"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4dmini5tradoR?1")]
        public string db_contra {
            get {
                return ((string)(this["db_contra"]));
            }
            set {
                this["db_contra"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("aceria_db")]
        public string db_nombre {
            get {
                return ((string)(this["db_nombre"]));
            }
            set {
                this["db_nombre"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NumeroColada")]
        public string num_colada {
            get {
                return ((string)(this["num_colada"]));
            }
            set {
                this["num_colada"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Fecha")]
        public string fecha_colada {
            get {
                return ((string)(this["fecha_colada"]));
            }
            set {
                this["fecha_colada"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Hora")]
        public string hora_colada {
            get {
                return ((string)(this["hora_colada"]));
            }
            set {
                this["hora_colada"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CONTADOR")]
        public string dia_colada {
            get {
                return ((string)(this["dia_colada"]));
            }
            set {
                this["dia_colada"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Recargues")]
        public string recargue_col {
            get {
                return ((string)(this["recargue_col"]));
            }
            set {
                this["recargue_col"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("OxigenoLanceado")]
        public string oxlan_col {
            get {
                return ((string)(this["oxlan_col"]));
            }
            set {
                this["oxlan_col"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PesoTotal")]
        public string pesot_col {
            get {
                return ((string)(this["pesot_col"]));
            }
            set {
                this["pesot_col"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Antracita")]
        public string antracita_col {
            get {
                return ((string)(this["antracita_col"]));
            }
            set {
                this["antracita_col"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Grafito")]
        public string grafito_col {
            get {
                return ((string)(this["grafito_col"]));
            }
            set {
                this["grafito_col"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TotalCarbon")]
        public string tcarbon_col {
            get {
                return ((string)(this["tcarbon_col"]));
            }
            set {
                this["tcarbon_col"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Gasoleo")]
        public string gasoleo_col {
            get {
                return ((string)(this["gasoleo_col"]));
            }
            set {
                this["gasoleo_col"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GLP")]
        public string glp_col {
            get {
                return ((string)(this["glp_col"]));
            }
            set {
                this["glp_col"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Oxigeno")]
        public string ox_col {
            get {
                return ((string)(this["ox_col"]));
            }
            set {
                this["ox_col"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Espumante")]
        public string espuma_col {
            get {
                return ((string)(this["espuma_col"]));
            }
            set {
                this["espuma_col"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("KWHFusion")]
        public string fusion_col {
            get {
                return ((string)(this["fusion_col"]));
            }
            set {
                this["fusion_col"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TiempoFusion")]
        public string tfusion_col {
            get {
                return ((string)(this["tfusion_col"]));
            }
            set {
                this["tfusion_col"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("KWHAfino")]
        public string afino_col {
            get {
                return ((string)(this["afino_col"]));
            }
            set {
                this["afino_col"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TiempoAfino")]
        public string tafino_col {
            get {
                return ((string)(this["tafino_col"]));
            }
            set {
                this["tafino_col"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("KWHTotal")]
        public string kwtotal_col {
            get {
                return ((string)(this["kwtotal_col"]));
            }
            set {
                this["kwtotal_col"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PowerON")]
        public string pon_col {
            get {
                return ((string)(this["pon_col"]));
            }
            set {
                this["pon_col"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PowerOff")]
        public string poff_col {
            get {
                return ((string)(this["poff_col"]));
            }
            set {
                this["poff_col"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Carbon")]
        public string carbon_col {
            get {
                return ((string)(this["carbon_col"]));
            }
            set {
                this["carbon_col"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TemperaturaFinal")]
        public string tempfinal_col {
            get {
                return ((string)(this["tempfinal_col"]));
            }
            set {
                this["tempfinal_col"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TiempoTotal")]
        public string ttotal_col {
            get {
                return ((string)(this["ttotal_col"]));
            }
            set {
                this["ttotal_col"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("EndBrick")]
        public string endbrick_col {
            get {
                return ((string)(this["endbrick_col"]));
            }
            set {
                this["endbrick_col"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Grado")]
        public string grado_col {
            get {
                return ((string)(this["grado_col"]));
            }
            set {
                this["grado_col"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Fundidor")]
        public string fun_col {
            get {
                return ((string)(this["fun_col"]));
            }
            set {
                this["fun_col"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("JefeTurno")]
        public string jefe_col {
            get {
                return ((string)(this["jefe_col"]));
            }
            set {
                this["jefe_col"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("HoraInicio")]
        public string hinicio_col {
            get {
                return ((string)(this["hinicio_col"]));
            }
            set {
                this["hinicio_col"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TiempoVaciado")]
        public string tvaciado_col {
            get {
                return ((string)(this["tvaciado_col"]));
            }
            set {
                this["tvaciado_col"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Jornada")]
        public string jor_col {
            get {
                return ((string)(this["jor_col"]));
            }
            set {
                this["jor_col"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PrograSmart")]
        public string psmart_col {
            get {
                return ((string)(this["psmart_col"]));
            }
            set {
                this["psmart_col"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PrograDigit")]
        public string pdigit_col {
            get {
                return ((string)(this["pdigit_col"]));
            }
            set {
                this["pdigit_col"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PesoCesta1")]
        public string pcesta1_col {
            get {
                return ((string)(this["pcesta1_col"]));
            }
            set {
                this["pcesta1_col"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PesoCesta2")]
        public string pcesta2_col {
            get {
                return ((string)(this["pcesta2_col"]));
            }
            set {
                this["pcesta2_col"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PesoCesta3")]
        public string pcesta3_col {
            get {
                return ((string)(this["pcesta3_col"]));
            }
            set {
                this["pcesta3_col"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PesoCesta4")]
        public string pcesta4_col {
            get {
                return ((string)(this["pcesta4_col"]));
            }
            set {
                this["pcesta4_col"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PesoCesta5")]
        public string pcesta5_col {
            get {
                return ((string)(this["pcesta5_col"]));
            }
            set {
                this["pcesta5_col"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ColadasHorno")]
        public string horno_col {
            get {
                return ((string)(this["horno_col"]));
            }
            set {
                this["horno_col"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ColadasDelta")]
        public string delta_col {
            get {
                return ((string)(this["delta_col"]));
            }
            set {
                this["delta_col"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ColadasElec1")]
        public string celec1 {
            get {
                return ((string)(this["celec1"]));
            }
            set {
                this["celec1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ColadasElect2")]
        public string celec2 {
            get {
                return ((string)(this["celec2"]));
            }
            set {
                this["celec2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ColadasElect3")]
        public string celec3 {
            get {
                return ((string)(this["celec3"]));
            }
            set {
                this["celec3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CalDolomitica")]
        public string caldol_col {
            get {
                return ((string)(this["caldol_col"]));
            }
            set {
                this["caldol_col"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CalCalcitica")]
        public string calcal_col {
            get {
                return ((string)(this["calcal_col"]));
            }
            set {
                this["calcal_col"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Kalister")]
        public string kalister_col {
            get {
                return ((string)(this["kalister_col"]));
            }
            set {
                this["kalister_col"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Torta")]
        public string torta_col {
            get {
                return ((string)(this["torta_col"]));
            }
            set {
                this["torta_col"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TemperaturaCentro")]
        public string tempcen_col {
            get {
                return ((string)(this["tempcen_col"]));
            }
            set {
                this["tempcen_col"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TemperaturaEVT")]
        public string tempevt_col {
            get {
                return ((string)(this["tempevt_col"]));
            }
            set {
                this["tempevt_col"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TemperaturaPuerta")]
        public string temppuer_col {
            get {
                return ((string)(this["temppuer_col"]));
            }
            set {
                this["temppuer_col"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Temperatura12")]
        public string temp12_col {
            get {
                return ((string)(this["temp12_col"]));
            }
            set {
                this["temp12_col"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Temperatura23")]
        public string temp23_col {
            get {
                return ((string)(this["temp23_col"]));
            }
            set {
                this["temp23_col"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Temperatura31")]
        public string temp31_col {
            get {
                return ((string)(this["temp31_col"]));
            }
            set {
                this["temp31_col"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TiempoDeSellado")]
        public string tsellado_col {
            get {
                return ((string)(this["tsellado_col"]));
            }
            set {
                this["tsellado_col"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TiempoDeArmado")]
        public string tarmado_col {
            get {
                return ((string)(this["tarmado_col"]));
            }
            set {
                this["tarmado_col"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tiempo1Recargue")]
        public string t1recar_col {
            get {
                return ((string)(this["t1recar_col"]));
            }
            set {
                this["t1recar_col"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TiempoBovedaAbierta1rCarga")]
        public string tabierta1_col {
            get {
                return ((string)(this["tabierta1_col"]));
            }
            set {
                this["tabierta1_col"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tiempo2Recargue")]
        public string t2recar_col {
            get {
                return ((string)(this["t2recar_col"]));
            }
            set {
                this["t2recar_col"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TiempoBovedaAbierta2aCarga")]
        public string tabierta2_col {
            get {
                return ((string)(this["tabierta2_col"]));
            }
            set {
                this["tabierta2_col"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tiempo3Recargue")]
        public string t3recar_col {
            get {
                return ((string)(this["t3recar_col"]));
            }
            set {
                this["t3recar_col"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TiempoBovedaAbierta3aCarga")]
        public string tabierta3_col {
            get {
                return ((string)(this["tabierta3_col"]));
            }
            set {
                this["tabierta3_col"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tiempo4Recargue")]
        public string t4recar_col {
            get {
                return ((string)(this["t4recar_col"]));
            }
            set {
                this["t4recar_col"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TiempoBovedaAbierta4aCarga")]
        public string tabierta4_col {
            get {
                return ((string)(this["tabierta4_col"]));
            }
            set {
                this["tabierta4_col"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TiempoVaciado1")]
        public string tvaciado1_col {
            get {
                return ((string)(this["tvaciado1_col"]));
            }
            set {
                this["tvaciado1_col"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("KwhEspecificaC1")]
        public string espc1_col {
            get {
                return ((string)(this["espc1_col"]));
            }
            set {
                this["espc1_col"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("KwhEspecificaC2")]
        public string espc2_col {
            get {
                return ((string)(this["espc2_col"]));
            }
            set {
                this["espc2_col"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("KwhEspecificaC3")]
        public string espc3_col {
            get {
                return ((string)(this["espc3_col"]));
            }
            set {
                this["espc3_col"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("KwhEspecificaC4")]
        public string espc4_col {
            get {
                return ((string)(this["espc4_col"]));
            }
            set {
                this["espc4_col"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FechaT")]
        public string fecha_mcc {
            get {
                return ((string)(this["fecha_mcc"]));
            }
            set {
                this["fecha_mcc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("HoraT")]
        public string hora_mcc {
            get {
                return ((string)(this["hora_mcc"]));
            }
            set {
                this["hora_mcc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Peso1")]
        public string peso_mcc {
            get {
                return ((string)(this["peso_mcc"]));
            }
            set {
                this["peso_mcc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CantLingote")]
        public string lingotes_mcc {
            get {
                return ((string)(this["lingotes_mcc"]));
            }
            set {
                this["lingotes_mcc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PesoAcero")]
        public string pacero_mcc {
            get {
                return ((string)(this["pacero_mcc"]));
            }
            set {
                this["pacero_mcc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NumeroColada")]
        public string num_col_mcc {
            get {
                return ((string)(this["num_col_mcc"]));
            }
            set {
                this["num_col_mcc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string minuto {
            get {
                return ((string)(this["minuto"]));
            }
            set {
                this["minuto"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\\\Users\\\\HYSTOU\\\\Desktop\\\\carpeta\\\\consola_log.txt")]
        public string directorio_log {
            get {
                return ((string)(this["directorio_log"]));
            }
            set {
                this["directorio_log"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ton_acero.csv")]
        public string archivo_csv_mcc {
            get {
                return ((string)(this["archivo_csv_mcc"]));
            }
            set {
                this["archivo_csv_mcc"] = value;
            }
        }
    }
}
